// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface StateTransferResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chain.StateTransferResponse)
    com.google.protobuf.MessageOrBuilder {
}
